export const CodegoNationalities = [
  {
    id: "2",
    country_code: "AL",
    country_name: "Albania",
    phonecode: "355",
    status: "0",
    is_iban: "0",
  },
  {
    id: "3",
    country_code: "DZ",
    country_name: "Algeria",
    phonecode: "213",
    status: "0",
    is_iban: "0",
  },
  {
    id: "5",
    country_code: "AD",
    country_name: "Andorra",
    phonecode: "376",
    status: "0",
    is_iban: "0",
  },
  {
    id: "6",
    country_code: "AO",
    country_name: "Angola",
    phonecode: "244",
    status: "0",
    is_iban: "0",
  },
  {
    id: "8",
    country_code: "AQ",
    country_name: "Antarctica",
    phonecode: "672",
    status: "0",
    is_iban: "0",
  },
  {
    id: "10",
    country_code: "AR",
    country_name: "Argentina",
    phonecode: "54",
    status: "0",
    is_iban: "0",
  },
  {
    id: "11",
    country_code: "AM",
    country_name: "Armenia",
    phonecode: "374",
    status: "0",
    is_iban: "0",
  },
  {
    id: "12",
    country_code: "AW",
    country_name: "Aruba",
    phonecode: "297",
    status: "0",
    is_iban: "0",
  },
  {
    id: "13",
    country_code: "AU",
    country_name: "Australia",
    phonecode: "61",
    status: "0",
    is_iban: "0",
  },
  {
    id: "14",
    country_code: "AT",
    country_name: "Austria",
    phonecode: "43",
    status: "0",
    is_iban: "0",
  },
  {
    id: "15",
    country_code: "AZ",
    country_name: "Azerbaijan",
    phonecode: "994",
    status: "0",
    is_iban: "0",
  },
  {
    id: "17",
    country_code: "BH",
    country_name: "Bahrain",
    phonecode: "973",
    status: "0",
    is_iban: "0",
  },
  {
    id: "18",
    country_code: "BD",
    country_name: "Bangladesh",
    phonecode: "880",
    status: "0",
    is_iban: "0",
  },
  {
    id: "20",
    country_code: "BY",
    country_name: "Belarus",
    phonecode: "375",
    status: "0",
    is_iban: "0",
  },
  {
    id: "21",
    country_code: "BE",
    country_name: "Belgium",
    phonecode: "32",
    status: "0",
    is_iban: "0",
  },
  {
    id: "22",
    country_code: "BZ",
    country_name: "Belize",
    phonecode: "501",
    status: "0",
    is_iban: "0",
  },
  {
    id: "23",
    country_code: "BJ",
    country_name: "Benin",
    phonecode: "229",
    status: "0",
    is_iban: "0",
  },
  {
    id: "25",
    country_code: "BT",
    country_name: "Bhutan",
    phonecode: "975",
    status: "0",
    is_iban: "0",
  },
  {
    id: "26",
    country_code: "BO",
    country_name: "Bolivia",
    phonecode: "591",
    status: "0",
    is_iban: "0",
  },
  {
    id: "27",
    country_code: "BA",
    country_name: "Bosnia and Herzegovina",
    phonecode: "387",
    status: "0",
    is_iban: "0",
  },
  {
    id: "28",
    country_code: "BW",
    country_name: "Botswana",
    phonecode: "267",
    status: "0",
    is_iban: "0",
  },
  {
    id: "30",
    country_code: "BR",
    country_name: "Brazil",
    phonecode: "55",
    status: "0",
    is_iban: "0",
  },
  {
    id: "31",
    country_code: "IO",
    country_name: "British Indian Ocean Territory",
    phonecode: "246",
    status: "0",
    is_iban: "0",
  },
  {
    id: "33",
    country_code: "BG",
    country_name: "Bulgaria",
    phonecode: "359",
    status: "0",
    is_iban: "0",
  },
  {
    id: "34",
    country_code: "BF",
    country_name: "Burkina Faso",
    phonecode: "226",
    status: "0",
    is_iban: "0",
  },
  {
    id: "35",
    country_code: "BI",
    country_name: "Burundi",
    phonecode: "257",
    status: "0",
    is_iban: "0",
  },
  {
    id: "36",
    country_code: "KH",
    country_name: "Cambodia",
    phonecode: "855",
    status: "0",
    is_iban: "0",
  },
  {
    id: "37",
    country_code: "CM",
    country_name: "Cameroon",
    phonecode: "237",
    status: "0",
    is_iban: "0",
  },
  {
    id: "38",
    country_code: "CA",
    country_name: "Canada",
    phonecode: "1",
    status: "0",
    is_iban: "0",
  },
  {
    id: "39",
    country_code: "CV",
    country_name: "Cape Verde",
    phonecode: "238",
    status: "0",
    is_iban: "0",
  },
  {
    id: "41",
    country_code: "CF",
    country_name: "Central African Republic",
    phonecode: "236",
    status: "0",
    is_iban: "0",
  },
  {
    id: "42",
    country_code: "TD",
    country_name: "Chad",
    phonecode: "235",
    status: "0",
    is_iban: "0",
  },
  {
    id: "43",
    country_code: "CL",
    country_name: "Chile",
    phonecode: "56",
    status: "0",
    is_iban: "0",
  },
  {
    id: "44",
    country_code: "CN",
    country_name: "China",
    phonecode: "86",
    status: "0",
    is_iban: "0",
  },
  {
    id: "45",
    country_code: "CX",
    country_name: "Christmas Island",
    phonecode: "61",
    status: "0",
    is_iban: "0",
  },
  {
    id: "46",
    country_code: "CC",
    country_name: "Cocos (Keeling) Islands",
    phonecode: "61",
    status: "0",
    is_iban: "0",
  },
  {
    id: "47",
    country_code: "CO",
    country_name: "Colombia",
    phonecode: "57",
    status: "0",
    is_iban: "0",
  },
  {
    id: "48",
    country_code: "KM",
    country_name: "Comoros",
    phonecode: "269",
    status: "0",
    is_iban: "0",
  },
  {
    id: "50",
    country_code: "CK",
    country_name: "Cook Islands",
    phonecode: "682",
    status: "0",
    is_iban: "0",
  },
  {
    id: "51",
    country_code: "CR",
    country_name: "Costa Rica",
    phonecode: "506",
    status: "0",
    is_iban: "0",
  },
  {
    id: "53",
    country_code: "CU",
    country_name: "Cuba",
    phonecode: "53",
    status: "0",
    is_iban: "0",
  },
  {
    id: "54",
    country_code: "CY",
    country_name: "Cyprus",
    phonecode: "357",
    status: "0",
    is_iban: "0",
  },
  {
    id: "55",
    country_code: "CZ",
    country_name: "Czech Republic",
    phonecode: "420",
    status: "0",
    is_iban: "0",
  },
  {
    id: "56",
    country_code: "DK",
    country_name: "Denmark",
    phonecode: "45",
    status: "0",
    is_iban: "0",
  },
  {
    id: "57",
    country_code: "DJ",
    country_name: "Djibouti",
    phonecode: "253",
    status: "0",
    is_iban: "0",
  },
  {
    id: "60",
    country_code: "TP",
    country_name: "East Timor",
    phonecode: "670",
    status: "0",
    is_iban: "0",
  },
  {
    id: "61",
    country_code: "EC",
    country_name: "Ecuador",
    phonecode: "593",
    status: "0",
    is_iban: "0",
  },
  {
    id: "62",
    country_code: "EG",
    country_name: "Egypt",
    phonecode: "20",
    status: "0",
    is_iban: "0",
  },
  {
    id: "63",
    country_code: "SV",
    country_name: "El Salvador",
    phonecode: "503",
    status: "0",
    is_iban: "0",
  },
  {
    id: "64",
    country_code: "GQ",
    country_name: "Equatorial Guinea",
    phonecode: "240",
    status: "0",
    is_iban: "0",
  },
  {
    id: "65",
    country_code: "ER",
    country_name: "Eritrea",
    phonecode: "291",
    status: "0",
    is_iban: "0",
  },
  {
    id: "66",
    country_code: "EE",
    country_name: "Estonia",
    phonecode: "372",
    status: "0",
    is_iban: "0",
  },
  {
    id: "67",
    country_code: "ET",
    country_name: "Ethiopia",
    phonecode: "251",
    status: "0",
    is_iban: "0",
  },
  {
    id: "68",
    country_code: "FK",
    country_name: "Falkland Islands",
    phonecode: "500",
    status: "0",
    is_iban: "0",
  },
  {
    id: "69",
    country_code: "FO",
    country_name: "Faroe Islands",
    phonecode: "298",
    status: "0",
    is_iban: "0",
  },
  {
    id: "70",
    country_code: "FJ",
    country_name: "Fiji",
    phonecode: "679",
    status: "0",
    is_iban: "0",
  },
  {
    id: "71",
    country_code: "FI",
    country_name: "Finland",
    phonecode: "358",
    status: "0",
    is_iban: "0",
  },
  {
    id: "72",
    country_code: "FR",
    country_name: "France",
    phonecode: "33",
    status: "0",
    is_iban: "0",
  },
  {
    id: "75",
    country_code: "PF",
    country_name: "French Polynesia",
    phonecode: "689",
    status: "0",
    is_iban: "0",
  },
  {
    id: "77",
    country_code: "GA",
    country_name: "Gabon",
    phonecode: "241",
    status: "0",
    is_iban: "0",
  },
  {
    id: "78",
    country_code: "GM",
    country_name: "Gambia",
    phonecode: "220",
    status: "0",
    is_iban: "0",
  },
  {
    id: "79",
    country_code: "GE",
    country_name: "Georgia",
    phonecode: "995",
    status: "0",
    is_iban: "0",
  },
  {
    id: "80",
    country_code: "DE",
    country_name: "Germany",
    phonecode: "49",
    status: "0",
    is_iban: "0",
  },
  {
    id: "81",
    country_code: "GH",
    country_name: "Ghana",
    phonecode: "233",
    status: "0",
    is_iban: "0",
  },
  {
    id: "82",
    country_code: "GI",
    country_name: "Gibraltar",
    phonecode: "350",
    status: "0",
    is_iban: "0",
  },
  {
    id: "84",
    country_code: "GR",
    country_name: "Greece",
    phonecode: "30",
    status: "0",
    is_iban: "0",
  },
  {
    id: "85",
    country_code: "GL",
    country_name: "Greenland",
    phonecode: "299",
    status: "0",
    is_iban: "0",
  },
  {
    id: "89",
    country_code: "GT",
    country_name: "Guatemala",
    phonecode: "502",
    status: "0",
    is_iban: "0",
  },
  {
    id: "90",
    country_code: "GN",
    country_name: "Guinea",
    phonecode: "224",
    status: "0",
    is_iban: "0",
  },
  {
    id: "91",
    country_code: "GW",
    country_name: "Guinea-Bissau",
    phonecode: "245",
    status: "0",
    is_iban: "0",
  },
  {
    id: "92",
    country_code: "GY",
    country_name: "Guyana",
    phonecode: "592",
    status: "0",
    is_iban: "0",
  },
  {
    id: "93",
    country_code: "HT",
    country_name: "Haiti",
    phonecode: "509",
    status: "0",
    is_iban: "0",
  },
  {
    id: "94",
    country_code: "HM",
    country_name: "Heard and Mc Donald Islands",
    phonecode: "504",
    status: "0",
    is_iban: "0",
  },
  {
    id: "96",
    country_code: "HK",
    country_name: "Hong Kong",
    phonecode: "852",
    status: "0",
    is_iban: "0",
  },
  {
    id: "97",
    country_code: "HU",
    country_name: "Hungary",
    phonecode: "36",
    status: "0",
    is_iban: "0",
  },
  {
    id: "98",
    country_code: "IS",
    country_name: "Iceland",
    phonecode: "354",
    status: "0",
    is_iban: "0",
  },
  {
    id: "99",
    country_code: "IN",
    country_name: "India",
    phonecode: "91",
    status: "1",
    is_iban: "0",
  },
  {
    id: "101",
    country_code: "ID",
    country_name: "Indonesia",
    phonecode: "62",
    status: "0",
    is_iban: "0",
  },
  {
    id: "102",
    country_code: "IR",
    country_name: "Iran (Islamic Republic of)",
    phonecode: "98",
    status: "0",
    is_iban: "0",
  },
  {
    id: "104",
    country_code: "IE",
    country_name: "Ireland",
    phonecode: "353",
    status: "0",
    is_iban: "0",
  },
  {
    id: "105",
    country_code: "IL",
    country_name: "Israel",
    phonecode: "972",
    status: "0",
    is_iban: "0",
  },
  {
    id: "106",
    country_code: "IT",
    country_name: "Italy",
    phonecode: "39",
    status: "1",
    is_iban: "1",
  },
  {
    id: "110",
    country_code: "JP",
    country_name: "Japan",
    phonecode: "81",
    status: "0",
    is_iban: "0",
  },
  {
    id: "111",
    country_code: "JO",
    country_name: "Jordan",
    phonecode: "962",
    status: "0",
    is_iban: "0",
  },
  {
    id: "112",
    country_code: "KZ",
    country_name: "Kazakhstan",
    phonecode: "7",
    status: "0",
    is_iban: "0",
  },
  {
    id: "113",
    country_code: "KE",
    country_name: "Kenya",
    phonecode: "254",
    status: "0",
    is_iban: "0",
  },
  {
    id: "114",
    country_code: "KI",
    country_name: "Kiribati",
    phonecode: "686",
    status: "0",
    is_iban: "0",
  },
  {
    id: "118",
    country_code: "KW",
    country_name: "Kuwait",
    phonecode: "965",
    status: "0",
    is_iban: "0",
  },
  {
    id: "119",
    country_code: "KG",
    country_name: "Kyrgyzstan",
    phonecode: "996",
    status: "0",
    is_iban: "0",
  },
  {
    id: "121",
    country_code: "LV",
    country_name: "Latvia",
    phonecode: "371",
    status: "0",
    is_iban: "0",
  },
  {
    id: "122",
    country_code: "LB",
    country_name: "Lebanon",
    phonecode: "961",
    status: "0",
    is_iban: "0",
  },
  {
    id: "123",
    country_code: "LS",
    country_name: "Lesotho",
    phonecode: "266",
    status: "0",
    is_iban: "0",
  },
  {
    id: "124",
    country_code: "LR",
    country_name: "Liberia",
    phonecode: "231",
    status: "0",
    is_iban: "0",
  },
  {
    id: "126",
    country_code: "LI",
    country_name: "Liechtenstein",
    phonecode: "423",
    status: "0",
    is_iban: "0",
  },
  {
    id: "127",
    country_code: "LT",
    country_name: "Lithuania",
    phonecode: "370",
    status: "0",
    is_iban: "0",
  },
  {
    id: "129",
    country_code: "MO",
    country_name: "Macau",
    phonecode: "853",
    status: "0",
    is_iban: "0",
  },
  {
    id: "130",
    country_code: "MK",
    country_name: "Macedonia",
    phonecode: "389",
    status: "0",
    is_iban: "0",
  },
  {
    id: "131",
    country_code: "MG",
    country_name: "Madagascar",
    phonecode: "261",
    status: "0",
    is_iban: "0",
  },
  {
    id: "132",
    country_code: "MW",
    country_name: "Malawi",
    phonecode: "265",
    status: "0",
    is_iban: "0",
  },
  {
    id: "133",
    country_code: "MY",
    country_name: "Malaysia",
    phonecode: "60",
    status: "0",
    is_iban: "0",
  },
  {
    id: "134",
    country_code: "MV",
    country_name: "Maldives",
    phonecode: "960",
    status: "0",
    is_iban: "0",
  },
  {
    id: "135",
    country_code: "ML",
    country_name: "Mali",
    phonecode: "223",
    status: "0",
    is_iban: "0",
  },
  {
    id: "136",
    country_code: "MT",
    country_name: "Malta",
    phonecode: "356",
    status: "0",
    is_iban: "0",
  },
  {
    id: "142",
    country_code: "MX",
    country_name: "Mexico",
    phonecode: "52",
    status: "0",
    is_iban: "0",
  },
  {
    id: "144",
    country_code: "MD",
    country_name: "Moldova, Republic of",
    phonecode: "373",
    status: "0",
    is_iban: "0",
  },
  {
    id: "145",
    country_code: "MC",
    country_name: "Monaco",
    phonecode: "377",
    status: "0",
    is_iban: "0",
  },
  {
    id: "146",
    country_code: "MN",
    country_name: "Mongolia",
    phonecode: "976",
    status: "0",
    is_iban: "0",
  },
  {
    id: "147",
    country_code: "ME",
    country_name: "Montenegro",
    phonecode: "382",
    status: "0",
    is_iban: "0",
  },
  {
    id: "149",
    country_code: "MA",
    country_name: "Morocco",
    phonecode: "212",
    status: "0",
    is_iban: "0",
  },
  {
    id: "150",
    country_code: "MZ",
    country_name: "Mozambique",
    phonecode: "258",
    status: "0",
    is_iban: "0",
  },
  {
    id: "151",
    country_code: "MM",
    country_name: "Myanmar",
    phonecode: "95",
    status: "0",
    is_iban: "0",
  },
  {
    id: "152",
    country_code: "NA",
    country_name: "Namibia",
    phonecode: "264",
    status: "0",
    is_iban: "0",
  },
  {
    id: "153",
    country_code: "NR",
    country_name: "Nauru",
    phonecode: "674",
    status: "0",
    is_iban: "0",
  },
  {
    id: "154",
    country_code: "NP",
    country_name: "Nepal",
    phonecode: "977",
    status: "0",
    is_iban: "0",
  },
  {
    id: "155",
    country_code: "NL",
    country_name: "Netherlands",
    phonecode: "31",
    status: "0",
    is_iban: "0",
  },
  {
    id: "156",
    country_code: "AN",
    country_name: "Netherlands Antilles",
    phonecode: "599",
    status: "0",
    is_iban: "0",
  },
  {
    id: "157",
    country_code: "NC",
    country_name: "New Caledonia",
    phonecode: "687",
    status: "0",
    is_iban: "0",
  },
  {
    id: "158",
    country_code: "NZ",
    country_name: "New Zealand",
    phonecode: "64",
    status: "0",
    is_iban: "0",
  },
  {
    id: "160",
    country_code: "NE",
    country_name: "Niger",
    phonecode: "227",
    status: "0",
    is_iban: "0",
  },
  {
    id: "161",
    country_code: "NG",
    country_name: "Nigeria",
    phonecode: "234",
    status: "0",
    is_iban: "0",
  },
  {
    id: "165",
    country_code: "NO",
    country_name: "Norway",
    phonecode: "47",
    status: "0",
    is_iban: "0",
  },
  {
    id: "166",
    country_code: "OM",
    country_name: "Oman",
    phonecode: "968",
    status: "0",
    is_iban: "0",
  },
  {
    id: "167",
    country_code: "PK",
    country_name: "Pakistan",
    phonecode: "92",
    status: "1",
    is_iban: "0",
  },
  {
    id: "168",
    country_code: "PW",
    country_name: "Palau",
    phonecode: "680",
    status: "0",
    is_iban: "0",
  },
  {
    id: "169",
    country_code: "PS",
    country_name: "Palestine",
    phonecode: "970",
    status: "0",
    is_iban: "0",
  },
  {
    id: "170",
    country_code: "PA",
    country_name: "Panama",
    phonecode: "507",
    status: "0",
    is_iban: "0",
  },
  {
    id: "171",
    country_code: "PG",
    country_name: "Papua New Guinea",
    phonecode: "675",
    status: "0",
    is_iban: "0",
  },
  {
    id: "172",
    country_code: "PY",
    country_name: "Paraguay",
    phonecode: "595",
    status: "0",
    is_iban: "0",
  },
  {
    id: "173",
    country_code: "PE",
    country_name: "Peru",
    phonecode: "51",
    status: "0",
    is_iban: "0",
  },
  {
    id: "174",
    country_code: "PH",
    country_name: "Philippines",
    phonecode: "63",
    status: "0",
    is_iban: "0",
  },
  {
    id: "175",
    country_code: "PN",
    country_name: "Pitcairn",
    phonecode: "64",
    status: "0",
    is_iban: "0",
  },
  {
    id: "176",
    country_code: "PL",
    country_name: "Poland",
    phonecode: "48",
    status: "0",
    is_iban: "0",
  },
  {
    id: "177",
    country_code: "PT",
    country_name: "Portugal",
    phonecode: "351",
    status: "0",
    is_iban: "0",
  },
  {
    id: "179",
    country_code: "QA",
    country_name: "Qatar",
    phonecode: "974",
    status: "0",
    is_iban: "0",
  },
  {
    id: "181",
    country_code: "RO",
    country_name: "Romania",
    phonecode: "40",
    status: "0",
    is_iban: "0",
  },
  {
    id: "182",
    country_code: "RU",
    country_name: "Russian Federation",
    phonecode: "7",
    status: "0",
    is_iban: "0",
  },
  {
    id: "183",
    country_code: "RW",
    country_name: "Rwanda",
    phonecode: "250",
    status: "0",
    is_iban: "0",
  },
  {
    id: "187",
    country_code: "WS",
    country_name: "Samoa",
    phonecode: "685",
    status: "0",
    is_iban: "0",
  },
  {
    id: "188",
    country_code: "SM",
    country_name: "San Marino",
    phonecode: "378",
    status: "0",
    is_iban: "0",
  },
  {
    id: "190",
    country_code: "SA",
    country_name: "Saudi Arabia",
    phonecode: "966",
    status: "0",
    is_iban: "0",
  },
  {
    id: "191",
    country_code: "SN",
    country_name: "Senegal",
    phonecode: "221",
    status: "0",
    is_iban: "0",
  },
  {
    id: "192",
    country_code: "RS",
    country_name: "Serbia",
    phonecode: "381",
    status: "0",
    is_iban: "0",
  },
  {
    id: "193",
    country_code: "SC",
    country_name: "Seychelles",
    phonecode: "248",
    status: "0",
    is_iban: "0",
  },
  {
    id: "194",
    country_code: "SL",
    country_name: "Sierra Leone",
    phonecode: "232",
    status: "0",
    is_iban: "0",
  },
  {
    id: "195",
    country_code: "SG",
    country_name: "Singapore",
    phonecode: "65",
    status: "0",
    is_iban: "0",
  },
  {
    id: "196",
    country_code: "SK",
    country_name: "Slovakia",
    phonecode: "421",
    status: "0",
    is_iban: "0",
  },
  {
    id: "197",
    country_code: "SI",
    country_name: "Slovenia",
    phonecode: "386",
    status: "0",
    is_iban: "0",
  },
  {
    id: "198",
    country_code: "SB",
    country_name: "Solomon Islands",
    phonecode: "677",
    status: "0",
    is_iban: "0",
  },
  {
    id: "200",
    country_code: "ZA",
    country_name: "South Africa",
    phonecode: "27",
    status: "0",
    is_iban: "0",
  },
  {
    id: "202",
    country_code: "ES",
    country_name: "Spain",
    phonecode: "34",
    status: "0",
    is_iban: "0",
  },
  {
    id: "203",
    country_code: "LK",
    country_name: "Sri Lanka",
    phonecode: "94",
    status: "0",
    is_iban: "0",
  },
  {
    id: "204",
    country_code: "SH",
    country_name: "St. Helena",
    phonecode: "290",
    status: "0",
    is_iban: "0",
  },
  {
    id: "205",
    country_code: "PM",
    country_name: "St. Pierre and Miquelon",
    phonecode: "508",
    status: "0",
    is_iban: "0",
  },
  {
    id: "207",
    country_code: "SR",
    country_name: "Suriname",
    phonecode: "597",
    status: "0",
    is_iban: "0",
  },
  {
    id: "208",
    country_code: "SJ",
    country_name: "Svalbard and Jan Mayen Islands",
    phonecode: "47",
    status: "0",
    is_iban: "0",
  },
  {
    id: "209",
    country_code: "SZ",
    country_name: "Swaziland",
    phonecode: "268",
    status: "0",
    is_iban: "0",
  },
  {
    id: "210",
    country_code: "SE",
    country_name: "Sweden",
    phonecode: "46",
    status: "0",
    is_iban: "0",
  },
  {
    id: "211",
    country_code: "CH",
    country_name: "Switzerland",
    phonecode: "41",
    status: "0",
    is_iban: "0",
  },
  {
    id: "213",
    country_code: "TW",
    country_name: "Taiwan",
    phonecode: "886",
    status: "0",
    is_iban: "0",
  },
  {
    id: "214",
    country_code: "TJ",
    country_name: "Tajikistan",
    phonecode: "992",
    status: "0",
    is_iban: "0",
  },
  {
    id: "215",
    country_code: "TZ",
    country_name: "Tanzania, United Republic of",
    phonecode: "255",
    status: "0",
    is_iban: "0",
  },
  {
    id: "216",
    country_code: "TH",
    country_name: "Thailand",
    phonecode: "66",
    status: "0",
    is_iban: "0",
  },
  {
    id: "217",
    country_code: "TG",
    country_name: "Togo",
    phonecode: "228",
    status: "0",
    is_iban: "0",
  },
  {
    id: "218",
    country_code: "TK",
    country_name: "Tokelau",
    phonecode: "690",
    status: "0",
    is_iban: "0",
  },
  {
    id: "219",
    country_code: "TO",
    country_name: "Tonga",
    phonecode: "676",
    status: "0",
    is_iban: "0",
  },
  {
    id: "221",
    country_code: "TN",
    country_name: "Tunisia",
    phonecode: "216",
    status: "0",
    is_iban: "0",
  },
  {
    id: "222",
    country_code: "TR",
    country_name: "Turkey",
    phonecode: "90",
    status: "0",
    is_iban: "0",
  },
  {
    id: "223",
    country_code: "TM",
    country_name: "Turkmenistan",
    phonecode: "993",
    status: "0",
    is_iban: "0",
  },
  {
    id: "225",
    country_code: "TV",
    country_name: "Tuvalu",
    phonecode: "688",
    status: "0",
    is_iban: "0",
  },
  {
    id: "226",
    country_code: "UG",
    country_name: "Uganda",
    phonecode: "256",
    status: "0",
    is_iban: "0",
  },
  {
    id: "227",
    country_code: "UA",
    country_name: "Ukraine",
    phonecode: "380",
    status: "0",
    is_iban: "0",
  },
  {
    id: "228",
    country_code: "AE",
    country_name: "United Arab Emirates",
    phonecode: "971",
    status: "0",
    is_iban: "0",
  },
  {
    id: "229",
    country_code: "GB",
    country_name: "United Kingdom",
    phonecode: "44",
    status: "0",
    is_iban: "2",
  },
  {
    id: "230",
    country_code: "US",
    country_name: "United States",
    phonecode: "1",
    status: "0",
    is_iban: "0",
  },
  {
    id: "232",
    country_code: "UY",
    country_name: "Uruguay",
    phonecode: "598",
    status: "0",
    is_iban: "0",
  },
  {
    id: "233",
    country_code: "UZ",
    country_name: "Uzbekistan",
    phonecode: "998",
    status: "0",
    is_iban: "0",
  },
  {
    id: "234",
    country_code: "VU",
    country_name: "Vanuatu",
    phonecode: "678",
    status: "0",
    is_iban: "0",
  },
  {
    id: "235",
    country_code: "VA",
    country_name: "Vatican City State",
    phonecode: "379",
    status: "0",
    is_iban: "0",
  },
  {
    id: "236",
    country_code: "VE",
    country_name: "Venezuela",
    phonecode: "58",
    status: "0",
    is_iban: "0",
  },
  {
    id: "237",
    country_code: "VN",
    country_name: "Vietnam",
    phonecode: "84",
    status: "0",
    is_iban: "0",
  },
  {
    id: "240",
    country_code: "WF",
    country_name: "Wallis and Futuna Islands",
    phonecode: "681",
    status: "0",
    is_iban: "0",
  },
  {
    id: "241",
    country_code: "EH",
    country_name: "Western Sahara",
    phonecode: "212",
    status: "0",
    is_iban: "0",
  },
  {
    id: "242",
    country_code: "YE",
    country_name: "Yemen",
    phonecode: "967",
    status: "0",
    is_iban: "0",
  },
  {
    id: "243",
    country_code: "ZR",
    country_name: "Zaire",
    phonecode: "967",
    status: "0",
    is_iban: "0",
  },
  {
    id: "244",
    country_code: "ZM",
    country_name: "Zambia",
    phonecode: "260",
    status: "0",
    is_iban: "0",
  },
  {
    id: "245",
    country_code: "LB",
    country_name: "Luxembourg",
    phonecode: "352",
    status: "0",
    is_iban: "0",
  },
  {
    id: "248",
    country_code: "IQ",
    country_name: "Iraq",
    phonecode: "964",
    status: "0",
    is_iban: "0",
  },
];
export const CodegoCountries = [
  {
    id: "2",
    country_code: "AL",
    country_name: "Albania",
    phonecode: "355",
    iso3: "008",
    status: "0",
    is_iban: "1",
    europe_country: "0",
    solaris_iban: "0",
    shipping_cost: "5",
    shipping_cost_usd: "20.00",
    flag: "🇦🇱",
  },
  {
    id: "3",
    country_code: "DZ",
    country_name: "Algeria",
    phonecode: "213",
    iso3: "012",
    status: "0",
    is_iban: "0",
    europe_country: "0",
    solaris_iban: "0",
    shipping_cost: "5",
    shipping_cost_usd: "20.00",
    flag: "🇩🇿",
  },
  {
    id: "5",
    country_code: "AD",
    country_name: "Andorra",
    phonecode: "376",
    iso3: "020",
    status: "0",
    is_iban: "1",
    europe_country: "1",
    solaris_iban: "0",
    shipping_cost: "5",
    shipping_cost_usd: "20.00",
    flag: "🇦🇩",
  },
  {
    id: "6",
    country_code: "AO",
    country_name: "Angola",
    phonecode: "244",
    iso3: "024",
    status: "0",
    is_iban: "0",
    europe_country: "0",
    solaris_iban: "0",
    shipping_cost: "5",
    shipping_cost_usd: "20.00",
    flag: "🇦🇴",
  },
  {
    id: "8",
    country_code: "AQ",
    country_name: "Antarctica",
    phonecode: "672",
    iso3: "010",
    status: "0",
    is_iban: "0",
    europe_country: "0",
    solaris_iban: "0",
    shipping_cost: "5",
    shipping_cost_usd: "20.00",
    flag: "🇦🇶",
  },
  {
    id: "10",
    country_code: "AR",
    country_name: "Argentina",
    phonecode: "54",
    iso3: "032",
    status: "0",
    is_iban: "0",
    europe_country: "0",
    solaris_iban: "0",
    shipping_cost: "5",
    shipping_cost_usd: "20.00",
    flag: "🇦🇷",
  },
  {
    id: "11",
    country_code: "AM",
    country_name: "Armenia",
    phonecode: "374",
    iso3: "051",
    status: "0",
    is_iban: "1",
    europe_country: "1",
    solaris_iban: "0",
    shipping_cost: "5",
    shipping_cost_usd: "20.00",
    flag: "🇦🇲",
  },
  {
    id: "13",
    country_code: "AU",
    country_name: "Australia",
    phonecode: "61",
    iso3: "036",
    status: "1",
    is_iban: "0",
    europe_country: "0",
    solaris_iban: "0",
    shipping_cost: "5",
    shipping_cost_usd: "20.00",
    flag: "🇦🇺",
  },
  {
    id: "14",
    country_code: "AT",
    country_name: "Austria",
    phonecode: "43",
    iso3: "040",
    status: "0",
    is_iban: "1",
    europe_country: "1",
    solaris_iban: "0",
    shipping_cost: "5",
    shipping_cost_usd: "20.00",
    flag: "🇦🇹",
  },
  {
    id: "15",
    country_code: "AZ",
    country_name: "Azerbaijan",
    phonecode: "994",
    iso3: "031",
    status: "0",
    is_iban: "0",
    europe_country: "0",
    solaris_iban: "0",
    shipping_cost: "5",
    shipping_cost_usd: "20.00",
    flag: "🇦🇿",
  },
  {
    id: "17",
    country_code: "BH",
    country_name: "Bahrain",
    phonecode: "973",
    iso3: "048",
    status: "0",
    is_iban: "0",
    europe_country: "0",
    solaris_iban: "0",
    shipping_cost: "5",
    shipping_cost_usd: "20.00",
    flag: "🇧🇭",
  },
  {
    id: "18",
    country_code: "BD",
    country_name: "Bangladesh",
    phonecode: "880",
    iso3: "050",
    status: "0",
    is_iban: "0",
    europe_country: "0",
    solaris_iban: "0",
    shipping_cost: "5",
    shipping_cost_usd: "20.00",
    flag: "🇧🇩",
  },
  {
    id: "20",
    country_code: "BY",
    country_name: "Belarus",
    phonecode: "375",
    iso3: "112",
    status: "0",
    is_iban: "1",
    europe_country: "0",
    solaris_iban: "0",
    shipping_cost: "5",
    shipping_cost_usd: "20.00",
    flag: "🇧🇾",
  },
  {
    id: "21",
    country_code: "BE",
    country_name: "Belgium",
    phonecode: "32",
    iso3: "056",
    status: "0",
    is_iban: "1",
    europe_country: "1",
    solaris_iban: "0",
    shipping_cost: "5",
    shipping_cost_usd: "20.00",
    flag: "🇧🇪",
  },
  {
    id: "22",
    country_code: "BZ",
    country_name: "Belize",
    phonecode: "501",
    iso3: "084",
    status: "0",
    is_iban: "0",
    europe_country: "0",
    solaris_iban: "0",
    shipping_cost: "5",
    shipping_cost_usd: "20.00",
    flag: "🇧🇿",
  },
  {
    id: "23",
    country_code: "BJ",
    country_name: "Benin",
    phonecode: "229",
    iso3: "204",
    status: "0",
    is_iban: "0",
    europe_country: "0",
    solaris_iban: "0",
    shipping_cost: "5",
    shipping_cost_usd: "20.00",
    flag: "🇧🇯",
  },
  {
    id: "25",
    country_code: "BT",
    country_name: "Bhutan",
    phonecode: "975",
    iso3: "064",
    status: "0",
    is_iban: "0",
    europe_country: "0",
    solaris_iban: "0",
    shipping_cost: "5",
    shipping_cost_usd: "20.00",
    flag: "🇧🇹",
  },
  {
    id: "26",
    country_code: "BO",
    country_name: "Bolivia",
    phonecode: "591",
    iso3: "068",
    status: "0",
    is_iban: "0",
    europe_country: "0",
    solaris_iban: "0",
    shipping_cost: "5",
    shipping_cost_usd: "20.00",
    flag: "🇧🇴",
  },
  {
    id: "27",
    country_code: "BA",
    country_name: "Bosnia and Herzegovina",
    phonecode: "387",
    iso3: "070",
    status: "0",
    is_iban: "1",
    europe_country: "0",
    solaris_iban: "0",
    shipping_cost: "5",
    shipping_cost_usd: "20.00",
    flag: "🇧🇦",
  },
  {
    id: "28",
    country_code: "BW",
    country_name: "Botswana",
    phonecode: "267",
    iso3: "072",
    status: "0",
    is_iban: "0",
    europe_country: "0",
    solaris_iban: "0",
    shipping_cost: "5",
    shipping_cost_usd: "20.00",
    flag: "🇧🇼",
  },
  {
    id: "30",
    country_code: "BR",
    country_name: "Brazil",
    phonecode: "55",
    iso3: "076",
    status: "0",
    is_iban: "0",
    europe_country: "0",
    solaris_iban: "0",
    shipping_cost: "5",
    shipping_cost_usd: "20.00",
    flag: "🇧🇷",
  },
  {
    id: "31",
    country_code: "IO",
    country_name: "British Indian Ocean Territory",
    phonecode: "246",
    iso3: "086",
    status: "0",
    is_iban: "0",
    europe_country: "0",
    solaris_iban: "0",
    shipping_cost: "5",
    shipping_cost_usd: "20.00",
    flag: "🇮🇴",
  },
  {
    id: "33",
    country_code: "BG",
    country_name: "Bulgaria",
    phonecode: "359",
    iso3: "100",
    status: "0",
    is_iban: "1",
    europe_country: "1",
    solaris_iban: "0",
    shipping_cost: "5",
    shipping_cost_usd: "20.00",
    flag: "🇧🇬",
  },
  {
    id: "34",
    country_code: "BF",
    country_name: "Burkina Faso",
    phonecode: "226",
    iso3: "854",
    status: "0",
    is_iban: "0",
    europe_country: "0",
    solaris_iban: "0",
    shipping_cost: "5",
    shipping_cost_usd: "20.00",
    flag: "🇧🇫",
  },
  {
    id: "35",
    country_code: "BI",
    country_name: "Burundi",
    phonecode: "257",
    iso3: "108",
    status: "0",
    is_iban: "0",
    europe_country: "0",
    solaris_iban: "0",
    shipping_cost: "5",
    shipping_cost_usd: "20.00",
    flag: "🇧🇮",
  },
  {
    id: "36",
    country_code: "KH",
    country_name: "Cambodia",
    phonecode: "855",
    iso3: "116",
    status: "0",
    is_iban: "0",
    europe_country: "0",
    solaris_iban: "0",
    shipping_cost: "5",
    shipping_cost_usd: "20.00",
    flag: "🇰🇭",
  },
  {
    id: "37",
    country_code: "CM",
    country_name: "Cameroon",
    phonecode: "237",
    iso3: "120",
    status: "0",
    is_iban: "0",
    europe_country: "0",
    solaris_iban: "0",
    shipping_cost: "5",
    shipping_cost_usd: "20.00",
    flag: "🇨🇲",
  },
  {
    id: "38",
    country_code: "CA",
    country_name: "Canada",
    phonecode: "1",
    iso3: "124",
    status: "0",
    is_iban: "0",
    europe_country: "0",
    solaris_iban: "0",
    shipping_cost: "5",
    shipping_cost_usd: "20.00",
    flag: "🇨🇦",
  },
  {
    id: "39",
    country_code: "CV",
    country_name: "Cape Verde",
    phonecode: "238",
    iso3: "132",
    status: "0",
    is_iban: "0",
    europe_country: "0",
    solaris_iban: "0",
    shipping_cost: "5",
    shipping_cost_usd: "20.00",
    flag: "🇨🇻",
  },
  {
    id: "41",
    country_code: "CF",
    country_name: "Central African Republic",
    phonecode: "236",
    iso3: "140",
    status: "0",
    is_iban: "0",
    europe_country: "0",
    solaris_iban: "0",
    shipping_cost: "5",
    shipping_cost_usd: "20.00",
    flag: "🇨🇫",
  },
  {
    id: "42",
    country_code: "TD",
    country_name: "Chad",
    phonecode: "235",
    iso3: "148",
    status: "0",
    is_iban: "0",
    europe_country: "0",
    solaris_iban: "0",
    shipping_cost: "5",
    shipping_cost_usd: "20.00",
    flag: "🇹🇩",
  },
  {
    id: "43",
    country_code: "CL",
    country_name: "Chile",
    phonecode: "56",
    iso3: "152",
    status: "0",
    is_iban: "0",
    europe_country: "0",
    solaris_iban: "0",
    shipping_cost: "5",
    shipping_cost_usd: "20.00",
    flag: "🇨🇱",
  },
  {
    id: "44",
    country_code: "CN",
    country_name: "China",
    phonecode: "86",
    iso3: "156",
    status: "0",
    is_iban: "0",
    europe_country: "0",
    solaris_iban: "0",
    shipping_cost: "5",
    shipping_cost_usd: "20.00",
    flag: "🇨🇳",
  },
  {
    id: "45",
    country_code: "CX",
    country_name: "Christmas Island",
    phonecode: "61",
    iso3: "162",
    status: "0",
    is_iban: "0",
    europe_country: "0",
    solaris_iban: "0",
    shipping_cost: "5",
    shipping_cost_usd: "20.00",
    flag: "🇨🇽",
  },
  {
    id: "46",
    country_code: "CC",
    country_name: "Cocos (Keeling) Islands",
    phonecode: "61",
    iso3: "166",
    status: "0",
    is_iban: "0",
    europe_country: "0",
    solaris_iban: "0",
    shipping_cost: "5",
    shipping_cost_usd: "20.00",
    flag: "🇨🇨",
  },
  {
    id: "47",
    country_code: "CO",
    country_name: "Colombia",
    phonecode: "57",
    iso3: "170",
    status: "0",
    is_iban: "0",
    europe_country: "0",
    solaris_iban: "0",
    shipping_cost: "5",
    shipping_cost_usd: "20.00",
    flag: "🇨🇴",
  },
  {
    id: "48",
    country_code: "KM",
    country_name: "Comoros",
    phonecode: "269",
    iso3: "174",
    status: "0",
    is_iban: "0",
    europe_country: "0",
    solaris_iban: "0",
    shipping_cost: "5",
    shipping_cost_usd: "20.00",
    flag: "🇰🇲",
  },
  {
    id: "50",
    country_code: "CK",
    country_name: "Cook Islands",
    phonecode: "682",
    iso3: "184",
    status: "0",
    is_iban: "0",
    europe_country: "0",
    solaris_iban: "0",
    shipping_cost: "5",
    shipping_cost_usd: "20.00",
    flag: "🇨🇰",
  },
  {
    id: "51",
    country_code: "CR",
    country_name: "Costa Rica",
    phonecode: "506",
    iso3: "188",
    status: "0",
    is_iban: "0",
    europe_country: "0",
    solaris_iban: "0",
    shipping_cost: "5",
    shipping_cost_usd: "20.00",
    flag: "🇨🇷",
  },
  {
    id: "53",
    country_code: "CU",
    country_name: "Cuba",
    phonecode: "53",
    iso3: "192",
    status: "0",
    is_iban: "0",
    europe_country: "0",
    solaris_iban: "0",
    shipping_cost: "5",
    shipping_cost_usd: "20.00",
    flag: "🇨🇺",
  },
  {
    id: "54",
    country_code: "CY",
    country_name: "Cyprus",
    phonecode: "357",
    iso3: "196",
    status: "0",
    is_iban: "1",
    europe_country: "0",
    solaris_iban: "0",
    shipping_cost: "5",
    shipping_cost_usd: "20.00",
    flag: "🇨🇾",
  },
  {
    id: "247",
    country_code: "CY",
    country_name: "Cyprus",
    phonecode: "357",
    iso3: "196",
    status: "0",
    is_iban: "1",
    europe_country: "1",
    solaris_iban: "0",
    shipping_cost: "5",
    shipping_cost_usd: "20.00",
    flag: "🇨🇾",
  },
  {
    id: "56",
    country_code: "DK",
    country_name: "Denmark",
    phonecode: "45",
    iso3: "208",
    status: "0",
    is_iban: "1",
    europe_country: "1",
    solaris_iban: "0",
    shipping_cost: "5",
    shipping_cost_usd: "20.00",
    flag: "🇩🇰",
  },
  {
    id: "57",
    country_code: "DJ",
    country_name: "Djibouti",
    phonecode: "253",
    iso3: "262",
    status: "0",
    is_iban: "0",
    europe_country: "0",
    solaris_iban: "0",
    shipping_cost: "5",
    shipping_cost_usd: "20.00",
    flag: "🇩🇯",
  },
  {
    id: "61",
    country_code: "EC",
    country_name: "Ecuador",
    phonecode: "593",
    iso3: "2018",
    status: "0",
    is_iban: "0",
    europe_country: "0",
    solaris_iban: "0",
    shipping_cost: "5",
    shipping_cost_usd: "20.00",
    flag: "🇪🇨",
  },
  {
    id: "62",
    country_code: "EG",
    country_name: "Egypt",
    phonecode: "20",
    iso3: "818",
    status: "1",
    is_iban: "0",
    europe_country: "0",
    solaris_iban: "0",
    shipping_cost: "5",
    shipping_cost_usd: "20.00",
    flag: "🇪🇬",
  },
  {
    id: "63",
    country_code: "SV",
    country_name: "El Salvador",
    phonecode: "503",
    iso3: "222",
    status: "0",
    is_iban: "0",
    europe_country: "0",
    solaris_iban: "0",
    shipping_cost: "5",
    shipping_cost_usd: "20.00",
    flag: "🇸🇻",
  },
  {
    id: "64",
    country_code: "GQ",
    country_name: "Equatorial Guinea",
    phonecode: "240",
    iso3: "226",
    status: "0",
    is_iban: "0",
    europe_country: "0",
    solaris_iban: "0",
    shipping_cost: "5",
    shipping_cost_usd: "20.00",
    flag: "🇬🇶",
  },
  {
    id: "65",
    country_code: "ER",
    country_name: "Eritrea",
    phonecode: "291",
    iso3: "232",
    status: "0",
    is_iban: "0",
    europe_country: "0",
    solaris_iban: "0",
    shipping_cost: "5",
    shipping_cost_usd: "20.00",
    flag: "🇪🇷",
  },
  {
    id: "66",
    country_code: "EE",
    country_name: "Estonia",
    phonecode: "372",
    iso3: "233",
    status: "0",
    is_iban: "1",
    europe_country: "1",
    solaris_iban: "0",
    shipping_cost: "5",
    shipping_cost_usd: "20.00",
    flag: "🇪🇪",
  },
  {
    id: "67",
    country_code: "ET",
    country_name: "Ethiopia",
    phonecode: "251",
    iso3: "231",
    status: "0",
    is_iban: "0",
    europe_country: "0",
    solaris_iban: "0",
    shipping_cost: "5",
    shipping_cost_usd: "20.00",
    flag: "🇪🇹",
  },
  {
    id: "71",
    country_code: "FI",
    country_name: "Finland",
    phonecode: "358",
    iso3: "246",
    status: "0",
    is_iban: "1",
    europe_country: "1",
    solaris_iban: "0",
    shipping_cost: "5",
    shipping_cost_usd: "20.00",
    flag: "🇫🇮",
  },
  {
    id: "72",
    country_code: "FR",
    country_name: "France",
    phonecode: "33",
    iso3: "250",
    status: "0",
    is_iban: "1",
    europe_country: "1",
    solaris_iban: "0",
    shipping_cost: "5",
    shipping_cost_usd: "20.00",
    flag: "🇫🇷",
  },
  {
    id: "75",
    country_code: "PF",
    country_name: "French Polynesia",
    phonecode: "689",
    iso3: "258",
    status: "0",
    is_iban: "0",
    europe_country: "0",
    solaris_iban: "0",
    shipping_cost: "5",
    shipping_cost_usd: "20.00",
    flag: "🇵🇫",
  },
  {
    id: "77",
    country_code: "GA",
    country_name: "Gabon",
    phonecode: "241",
    iso3: "266",
    status: "0",
    is_iban: "0",
    europe_country: "0",
    solaris_iban: "0",
    shipping_cost: "5",
    shipping_cost_usd: "20.00",
    flag: "🇬🇦",
  },
  {
    id: "78",
    country_code: "GM",
    country_name: "Gambia",
    phonecode: "220",
    iso3: "270",
    status: "0",
    is_iban: "0",
    europe_country: "0",
    solaris_iban: "0",
    shipping_cost: "5",
    shipping_cost_usd: "20.00",
    flag: "🇬🇲",
  },
  {
    id: "79",
    country_code: "GE",
    country_name: "Georgia",
    phonecode: "995",
    iso3: "268",
    status: "0",
    is_iban: "1",
    europe_country: "0",
    solaris_iban: "1",
    shipping_cost: "5",
    shipping_cost_usd: "20.00",
    flag: "🇬🇪",
  },
  {
    id: "80",
    country_code: "DE",
    country_name: "Germany",
    phonecode: "49",
    iso3: "276",
    status: "0",
    is_iban: "1",
    europe_country: "1",
    solaris_iban: "0",
    shipping_cost: "5",
    shipping_cost_usd: "20.00",
    flag: "🇩🇪",
  },
  {
    id: "81",
    country_code: "GH",
    country_name: "Ghana",
    phonecode: "233",
    iso3: "288",
    status: "0",
    is_iban: "0",
    europe_country: "0",
    solaris_iban: "0",
    shipping_cost: "5",
    shipping_cost_usd: "20.00",
    flag: "🇬🇭",
  },
  {
    id: "84",
    country_code: "GR",
    country_name: "Greece",
    phonecode: "30",
    iso3: "300",
    status: "0",
    is_iban: "1",
    europe_country: "1",
    solaris_iban: "0",
    shipping_cost: "5",
    shipping_cost_usd: "20.00",
    flag: "🇬🇷",
  },
  {
    id: "85",
    country_code: "GL",
    country_name: "Greenland",
    phonecode: "299",
    iso3: "304",
    status: "0",
    is_iban: "0",
    europe_country: "0",
    solaris_iban: "0",
    shipping_cost: "5",
    shipping_cost_usd: "20.00",
    flag: "🇬🇱",
  },
  {
    id: "89",
    country_code: "GT",
    country_name: "Guatemala",
    phonecode: "502",
    iso3: "320",
    status: "0",
    is_iban: "0",
    europe_country: "0",
    solaris_iban: "0",
    shipping_cost: "5",
    shipping_cost_usd: "20.00",
    flag: "🇬🇹",
  },
  {
    id: "90",
    country_code: "GN",
    country_name: "Guinea",
    phonecode: "224",
    iso3: "324",
    status: "0",
    is_iban: "0",
    europe_country: "0",
    solaris_iban: "0",
    shipping_cost: "5",
    shipping_cost_usd: "20.00",
    flag: "🇬🇳",
  },
  {
    id: "91",
    country_code: "GW",
    country_name: "Guinea-Bissau",
    phonecode: "245",
    iso3: "624",
    status: "0",
    is_iban: "0",
    europe_country: "0",
    solaris_iban: "0",
    shipping_cost: "5",
    shipping_cost_usd: "20.00",
    flag: "🇬🇼",
  },
  {
    id: "92",
    country_code: "GY",
    country_name: "Guyana",
    phonecode: "592",
    iso3: "328",
    status: "0",
    is_iban: "0",
    europe_country: "0",
    solaris_iban: "0",
    shipping_cost: "5",
    shipping_cost_usd: "20.00",
    flag: "🇬🇾",
  },
  {
    id: "93",
    country_code: "HT",
    country_name: "Haiti",
    phonecode: "509",
    iso3: "332",
    status: "0",
    is_iban: "0",
    europe_country: "0",
    solaris_iban: "0",
    shipping_cost: "5",
    shipping_cost_usd: "20.00",
    flag: "🇭🇹",
  },
  {
    id: "94",
    country_code: "HM",
    country_name: "Heard and Mc Donald Islands",
    phonecode: "504",
    iso3: "334",
    status: "0",
    is_iban: "0",
    europe_country: "0",
    solaris_iban: "0",
    shipping_cost: "5",
    shipping_cost_usd: "20.00",
    flag: "🇭🇲",
  },
  {
    id: "96",
    country_code: "HK",
    country_name: "Hong Kong",
    phonecode: "852",
    iso3: "344",
    status: "0",
    is_iban: "0",
    europe_country: "0",
    solaris_iban: "0",
    shipping_cost: "5",
    shipping_cost_usd: "20.00",
    flag: "🇭🇰",
  },
  {
    id: "97",
    country_code: "HU",
    country_name: "Hungary",
    phonecode: "36",
    iso3: "348",
    status: "0",
    is_iban: "1",
    europe_country: "1",
    solaris_iban: "0",
    shipping_cost: "5",
    shipping_cost_usd: "20.00",
    flag: "🇭🇺",
  },
  {
    id: "98",
    country_code: "IS",
    country_name: "Iceland",
    phonecode: "354",
    iso3: "352",
    status: "0",
    is_iban: "1",
    europe_country: "1",
    solaris_iban: "0",
    shipping_cost: "5",
    shipping_cost_usd: "20.00",
    flag: "🇮🇸",
  },
  {
    id: "99",
    country_code: "IN",
    country_name: "India",
    phonecode: "91",
    iso3: "356",
    status: "1",
    is_iban: "0",
    europe_country: "0",
    solaris_iban: "0",
    shipping_cost: "5",
    shipping_cost_usd: "20.00",
    flag: "🇮🇳",
  },
  {
    id: "101",
    country_code: "ID",
    country_name: "Indonesia",
    phonecode: "62",
    iso3: "360",
    status: "0",
    is_iban: "0",
    europe_country: "0",
    solaris_iban: "0",
    shipping_cost: "5",
    shipping_cost_usd: "20.00",
    flag: "🇮🇩",
  },
  {
    id: "102",
    country_code: "IR",
    country_name: "Iran (Islamic Republic of)",
    phonecode: "98",
    iso3: "364",
    status: "0",
    is_iban: "0",
    europe_country: "0",
    solaris_iban: "0",
    shipping_cost: "5",
    shipping_cost_usd: "20.00",
    flag: "🇮🇷",
  },
  {
    id: "248",
    country_code: "IQ",
    country_name: "Iraq",
    phonecode: "964",
    iso3: "368",
    status: "0",
    is_iban: "0",
    europe_country: "0",
    solaris_iban: "0",
    shipping_cost: "5",
    shipping_cost_usd: "20.00",
    flag: "🇮🇶",
  },
  {
    id: "104",
    country_code: "IE",
    country_name: "Ireland",
    phonecode: "353",
    iso3: "372",
    status: "0",
    is_iban: "1",
    europe_country: "1",
    solaris_iban: "0",
    shipping_cost: "5",
    shipping_cost_usd: "20.00",
    flag: "🇮🇪",
  },
  {
    id: "105",
    country_code: "IL",
    country_name: "Israel",
    phonecode: "972",
    iso3: "376",
    status: "0",
    is_iban: "0",
    europe_country: "0",
    solaris_iban: "0",
    shipping_cost: "5",
    shipping_cost_usd: "20.00",
    flag: "🇮🇱",
  },
  {
    id: "106",
    country_code: "IT",
    country_name: "Italy",
    phonecode: "39",
    iso3: "380",
    status: "1",
    is_iban: "1",
    europe_country: "1",
    solaris_iban: "1",
    shipping_cost: "5",
    shipping_cost_usd: "20.00",
    flag: "🇮🇹",
  },
  {
    id: "110",
    country_code: "JP",
    country_name: "Japan",
    phonecode: "81",
    iso3: "392",
    status: "0",
    is_iban: "0",
    europe_country: "0",
    solaris_iban: "0",
    shipping_cost: "5",
    shipping_cost_usd: "20.00",
    flag: "🇯🇵",
  },
  {
    id: "111",
    country_code: "JO",
    country_name: "Jordan",
    phonecode: "962",
    iso3: "400",
    status: "0",
    is_iban: "0",
    europe_country: "0",
    solaris_iban: "0",
    shipping_cost: "5",
    shipping_cost_usd: "20.00",
    flag: "🇯🇴",
  },
  {
    id: "112",
    country_code: "KZ",
    country_name: "Kazakhstan",
    phonecode: "7",
    iso3: "398",
    status: "0",
    is_iban: "0",
    europe_country: "0",
    solaris_iban: "0",
    shipping_cost: "5",
    shipping_cost_usd: "20.00",
    flag: "🇰🇿",
  },
  {
    id: "113",
    country_code: "KE",
    country_name: "Kenya",
    phonecode: "254",
    iso3: "404",
    status: "0",
    is_iban: "0",
    europe_country: "0",
    solaris_iban: "0",
    shipping_cost: "5",
    shipping_cost_usd: "20.00",
    flag: "🇰🇪",
  },
  {
    id: "114",
    country_code: "KI",
    country_name: "Kiribati",
    phonecode: "686",
    iso3: "296",
    status: "0",
    is_iban: "0",
    europe_country: "0",
    solaris_iban: "0",
    shipping_cost: "5",
    shipping_cost_usd: "20.00",
    flag: "🇰🇮",
  },
  {
    id: "118",
    country_code: "KW",
    country_name: "Kuwait",
    phonecode: "965",
    iso3: "414",
    status: "0",
    is_iban: "0",
    europe_country: "0",
    solaris_iban: "0",
    shipping_cost: "5",
    shipping_cost_usd: "20.00",
    flag: "🇰🇼",
  },
  {
    id: "119",
    country_code: "KG",
    country_name: "Kyrgyzstan",
    phonecode: "996",
    iso3: "417",
    status: "0",
    is_iban: "0",
    europe_country: "0",
    solaris_iban: "0",
    shipping_cost: "5",
    shipping_cost_usd: "20.00",
    flag: "🇰🇬",
  },
  {
    id: "121",
    country_code: "LV",
    country_name: "Latvia",
    phonecode: "371",
    iso3: "428",
    status: "0",
    is_iban: "1",
    europe_country: "1",
    solaris_iban: "0",
    shipping_cost: "5",
    shipping_cost_usd: "20.00",
    flag: "🇱🇻",
  },
  {
    id: "122",
    country_code: "LB",
    country_name: "Lebanon",
    phonecode: "961",
    iso3: "422",
    status: "0",
    is_iban: "0",
    europe_country: "0",
    solaris_iban: "0",
    shipping_cost: "5",
    shipping_cost_usd: "20.00",
    flag: "🇱🇧",
  },
  {
    id: "123",
    country_code: "LS",
    country_name: "Lesotho",
    phonecode: "266",
    iso3: "426",
    status: "0",
    is_iban: "0",
    europe_country: "0",
    solaris_iban: "0",
    shipping_cost: "5",
    shipping_cost_usd: "20.00",
    flag: "🇱🇸",
  },
  {
    id: "124",
    country_code: "LR",
    country_name: "Liberia",
    phonecode: "231",
    iso3: "430",
    status: "0",
    is_iban: "0",
    europe_country: "0",
    solaris_iban: "0",
    shipping_cost: "5",
    shipping_cost_usd: "20.00",
    flag: "🇱🇷",
  },
  {
    id: "126",
    country_code: "LI",
    country_name: "Liechtenstein",
    phonecode: "423",
    iso3: "438",
    status: "0",
    is_iban: "0",
    europe_country: "0",
    solaris_iban: "0",
    shipping_cost: "5",
    shipping_cost_usd: "20.00",
    flag: "🇱🇮",
  },
  {
    id: "127",
    country_code: "LT",
    country_name: "Lithuania",
    phonecode: "370",
    iso3: "440",
    status: "0",
    is_iban: "1",
    europe_country: "1",
    solaris_iban: "0",
    shipping_cost: "5",
    shipping_cost_usd: "20.00",
    flag: "🇱🇹",
  },
  {
    id: "245",
    country_code: "LB",
    country_name: "Luxembourg",
    phonecode: "352",
    iso3: "442",
    status: "0",
    is_iban: "1",
    europe_country: "1",
    solaris_iban: "0",
    shipping_cost: "5",
    shipping_cost_usd: "20.00",
    flag: "🇱🇧",
  },
  {
    id: "129",
    country_code: "MO",
    country_name: "Macau",
    phonecode: "853",
    iso3: "446",
    status: "0",
    is_iban: "0",
    europe_country: "0",
    solaris_iban: "0",
    shipping_cost: "5",
    shipping_cost_usd: "20.00",
    flag: "🇲🇴",
  },
  {
    id: "130",
    country_code: "MK",
    country_name: "Macedonia",
    phonecode: "389",
    iso3: "807",
    status: "0",
    is_iban: "1",
    europe_country: "1",
    solaris_iban: "0",
    shipping_cost: "5",
    shipping_cost_usd: "20.00",
    flag: "🇲🇰",
  },
  {
    id: "131",
    country_code: "MG",
    country_name: "Madagascar",
    phonecode: "261",
    iso3: "405",
    status: "0",
    is_iban: "0",
    europe_country: "0",
    solaris_iban: "0",
    shipping_cost: "5",
    shipping_cost_usd: "20.00",
    flag: "🇲🇬",
  },
  {
    id: "132",
    country_code: "MW",
    country_name: "Malawi",
    phonecode: "265",
    iso3: "454",
    status: "0",
    is_iban: "0",
    europe_country: "0",
    solaris_iban: "0",
    shipping_cost: "5",
    shipping_cost_usd: "20.00",
    flag: "🇲🇼",
  },
  {
    id: "133",
    country_code: "MY",
    country_name: "Malaysia",
    phonecode: "60",
    iso3: "458",
    status: "0",
    is_iban: "0",
    europe_country: "0",
    solaris_iban: "0",
    shipping_cost: "5",
    shipping_cost_usd: "20.00",
    flag: "🇲🇾",
  },
  {
    id: "134",
    country_code: "MV",
    country_name: "Maldives",
    phonecode: "960",
    iso3: "462",
    status: "0",
    is_iban: "0",
    europe_country: "0",
    solaris_iban: "0",
    shipping_cost: "5",
    shipping_cost_usd: "20.00",
    flag: "🇲🇻",
  },
  {
    id: "135",
    country_code: "ML",
    country_name: "Mali",
    phonecode: "223",
    iso3: "466",
    status: "0",
    is_iban: "0",
    europe_country: "0",
    solaris_iban: "0",
    shipping_cost: "5",
    shipping_cost_usd: "20.00",
    flag: "🇲🇱",
  },
  {
    id: "136",
    country_code: "MT",
    country_name: "Malta",
    phonecode: "356",
    iso3: "470",
    status: "0",
    is_iban: "1",
    europe_country: "1",
    solaris_iban: "0",
    shipping_cost: "5",
    shipping_cost_usd: "20.00",
    flag: "🇲🇹",
  },
  {
    id: "142",
    country_code: "MX",
    country_name: "Mexico",
    phonecode: "52",
    iso3: "484",
    status: "0",
    is_iban: "0",
    europe_country: "0",
    solaris_iban: "0",
    shipping_cost: "5",
    shipping_cost_usd: "20.00",
    flag: "🇲🇽",
  },
  {
    id: "144",
    country_code: "MD",
    country_name: "Moldova, Republic of",
    phonecode: "373",
    iso3: "498",
    status: "0",
    is_iban: "1",
    europe_country: "0",
    solaris_iban: "0",
    shipping_cost: "5",
    shipping_cost_usd: "20.00",
    flag: "🇲🇩",
  },
  {
    id: "145",
    country_code: "MC",
    country_name: "Monaco",
    phonecode: "377",
    iso3: "492",
    status: "0",
    is_iban: "1",
    europe_country: "1",
    solaris_iban: "0",
    shipping_cost: "5",
    shipping_cost_usd: "20.00",
    flag: "🇲🇨",
  },
  {
    id: "146",
    country_code: "MN",
    country_name: "Mongolia",
    phonecode: "976",
    iso3: "496",
    status: "0",
    is_iban: "0",
    europe_country: "0",
    solaris_iban: "0",
    shipping_cost: "5",
    shipping_cost_usd: "20.00",
    flag: "🇲🇳",
  },
  {
    id: "147",
    country_code: "ME",
    country_name: "Montenegro",
    phonecode: "382",
    iso3: "499",
    status: "0",
    is_iban: "1",
    europe_country: "1",
    solaris_iban: "0",
    shipping_cost: "5",
    shipping_cost_usd: "20.00",
    flag: "🇲🇪",
  },
  {
    id: "149",
    country_code: "MA",
    country_name: "Morocco",
    phonecode: "212",
    iso3: "504",
    status: "0",
    is_iban: "0",
    europe_country: "0",
    solaris_iban: "0",
    shipping_cost: "5",
    shipping_cost_usd: "20.00",
    flag: "🇲🇦",
  },
  {
    id: "150",
    country_code: "MZ",
    country_name: "Mozambique",
    phonecode: "258",
    iso3: "508",
    status: "0",
    is_iban: "0",
    europe_country: "0",
    solaris_iban: "0",
    shipping_cost: "5",
    shipping_cost_usd: "20.00",
    flag: "🇲🇿",
  },
  {
    id: "151",
    country_code: "MM",
    country_name: "Myanmar",
    phonecode: "95",
    iso3: "104",
    status: "0",
    is_iban: "0",
    europe_country: "0",
    solaris_iban: "0",
    shipping_cost: "5",
    shipping_cost_usd: "20.00",
    flag: "🇲🇲",
  },
  {
    id: "152",
    country_code: "NA",
    country_name: "Namibia",
    phonecode: "264",
    iso3: "516",
    status: "0",
    is_iban: "0",
    europe_country: "0",
    solaris_iban: "0",
    shipping_cost: "5",
    shipping_cost_usd: "20.00",
    flag: "🇳🇦",
  },
  {
    id: "153",
    country_code: "NR",
    country_name: "Nauru",
    phonecode: "674",
    iso3: "520",
    status: "0",
    is_iban: "0",
    europe_country: "0",
    solaris_iban: "0",
    shipping_cost: "5",
    shipping_cost_usd: "20.00",
    flag: "🇳🇷",
  },
  {
    id: "154",
    country_code: "NP",
    country_name: "Nepal",
    phonecode: "977",
    iso3: "524",
    status: "0",
    is_iban: "0",
    europe_country: "0",
    solaris_iban: "0",
    shipping_cost: "5",
    shipping_cost_usd: "20.00",
    flag: "🇳🇵",
  },
  {
    id: "155",
    country_code: "NL",
    country_name: "Netherlands",
    phonecode: "31",
    iso3: "528",
    status: "0",
    is_iban: "1",
    europe_country: "1",
    solaris_iban: "0",
    shipping_cost: "5",
    shipping_cost_usd: "20.00",
    flag: "🇳🇱",
  },
  {
    id: "158",
    country_code: "NZ",
    country_name: "New Zealand",
    phonecode: "64",
    iso3: "554",
    status: "0",
    is_iban: "0",
    europe_country: "0",
    solaris_iban: "0",
    shipping_cost: "5",
    shipping_cost_usd: "20.00",
    flag: "🇳🇿",
  },
  {
    id: "160",
    country_code: "NE",
    country_name: "Niger",
    phonecode: "227",
    iso3: "562",
    status: "0",
    is_iban: "0",
    europe_country: "0",
    solaris_iban: "0",
    shipping_cost: "5",
    shipping_cost_usd: "20.00",
    flag: "🇳🇪",
  },
  {
    id: "161",
    country_code: "NG",
    country_name: "Nigeria",
    phonecode: "234",
    iso3: "566",
    status: "0",
    is_iban: "0",
    europe_country: "0",
    solaris_iban: "0",
    shipping_cost: "5",
    shipping_cost_usd: "20.00",
    flag: "🇳🇬",
  },
  {
    id: "165",
    country_code: "NO",
    country_name: "Norway",
    phonecode: "47",
    iso3: "578",
    status: "0",
    is_iban: "1",
    europe_country: "1",
    solaris_iban: "0",
    shipping_cost: "5",
    shipping_cost_usd: "20.00",
    flag: "🇳🇴",
  },
  {
    id: "166",
    country_code: "OM",
    country_name: "Oman",
    phonecode: "968",
    iso3: "512",
    status: "0",
    is_iban: "0",
    europe_country: "0",
    solaris_iban: "0",
    shipping_cost: "5",
    shipping_cost_usd: "20.00",
    flag: "🇴🇲",
  },
  {
    id: "167",
    country_code: "PK",
    country_name: "Pakistan",
    phonecode: "92",
    iso3: "586",
    status: "1",
    is_iban: "0",
    europe_country: "0",
    solaris_iban: "0",
    shipping_cost: "5",
    shipping_cost_usd: "20.00",
    flag: "🇵🇰",
  },
  {
    id: "168",
    country_code: "PW",
    country_name: "Palau",
    phonecode: "680",
    iso3: "585",
    status: "0",
    is_iban: "0",
    europe_country: "0",
    solaris_iban: "0",
    shipping_cost: "5",
    shipping_cost_usd: "20.00",
    flag: "🇵🇼",
  },
  {
    id: "169",
    country_code: "PS",
    country_name: "Palestine",
    phonecode: "970",
    iso3: "275",
    status: "0",
    is_iban: "0",
    europe_country: "0",
    solaris_iban: "0",
    shipping_cost: "5",
    shipping_cost_usd: "20.00",
    flag: "🇵🇸",
  },
  {
    id: "170",
    country_code: "PA",
    country_name: "Panama",
    phonecode: "507",
    iso3: "591",
    status: "0",
    is_iban: "0",
    europe_country: "0",
    solaris_iban: "0",
    shipping_cost: "5",
    shipping_cost_usd: "20.00",
    flag: "🇵🇦",
  },
  {
    id: "171",
    country_code: "PG",
    country_name: "Papua New Guinea",
    phonecode: "675",
    iso3: "598",
    status: "0",
    is_iban: "0",
    europe_country: "0",
    solaris_iban: "0",
    shipping_cost: "5",
    shipping_cost_usd: "20.00",
    flag: "🇵🇬",
  },
  {
    id: "172",
    country_code: "PY",
    country_name: "Paraguay",
    phonecode: "595",
    iso3: "600",
    status: "0",
    is_iban: "0",
    europe_country: "0",
    solaris_iban: "0",
    shipping_cost: "5",
    shipping_cost_usd: "20.00",
    flag: "🇵🇾",
  },
  {
    id: "173",
    country_code: "PE",
    country_name: "Peru",
    phonecode: "51",
    iso3: "604",
    status: "0",
    is_iban: "0",
    europe_country: "0",
    solaris_iban: "0",
    shipping_cost: "5",
    shipping_cost_usd: "20.00",
    flag: "🇵🇪",
  },
  {
    id: "174",
    country_code: "PH",
    country_name: "Philippines",
    phonecode: "63",
    iso3: "608",
    status: "0",
    is_iban: "0",
    europe_country: "0",
    solaris_iban: "0",
    shipping_cost: "5",
    shipping_cost_usd: "20.00",
    flag: "🇵🇭",
  },
  {
    id: "175",
    country_code: "PN",
    country_name: "Pitcairn",
    phonecode: "64",
    iso3: "612",
    status: "0",
    is_iban: "0",
    europe_country: "0",
    solaris_iban: "0",
    shipping_cost: "5",
    shipping_cost_usd: "20.00",
    flag: "🇵🇳",
  },
  {
    id: "176",
    country_code: "PL",
    country_name: "Poland",
    phonecode: "48",
    iso3: "616",
    status: "0",
    is_iban: "1",
    europe_country: "1",
    solaris_iban: "0",
    shipping_cost: "5",
    shipping_cost_usd: "20.00",
    flag: "🇵🇱",
  },
  {
    id: "177",
    country_code: "PT",
    country_name: "Portugal",
    phonecode: "351",
    iso3: "620",
    status: "0",
    is_iban: "1",
    europe_country: "1",
    solaris_iban: "0",
    shipping_cost: "5",
    shipping_cost_usd: "20.00",
    flag: "🇵🇹",
  },
  {
    id: "179",
    country_code: "QA",
    country_name: "Qatar",
    phonecode: "974",
    iso3: "634",
    status: "0",
    is_iban: "0",
    europe_country: "0",
    solaris_iban: "0",
    shipping_cost: "5",
    shipping_cost_usd: "20.00",
    flag: "🇶🇦",
  },
  {
    id: "181",
    country_code: "RO",
    country_name: "Romania",
    phonecode: "40",
    iso3: "642",
    status: "0",
    is_iban: "1",
    europe_country: "1",
    solaris_iban: "0",
    shipping_cost: "5",
    shipping_cost_usd: "20.00",
    flag: "🇷🇴",
  },
  {
    id: "182",
    country_code: "RU",
    country_name: "Russian Federation",
    phonecode: "7",
    iso3: "643",
    status: "0",
    is_iban: "0",
    europe_country: "0",
    solaris_iban: "0",
    shipping_cost: "5",
    shipping_cost_usd: "20.00",
    flag: "🇷🇺",
  },
  {
    id: "183",
    country_code: "RW",
    country_name: "Rwanda",
    phonecode: "250",
    iso3: "646",
    status: "0",
    is_iban: "0",
    europe_country: "0",
    solaris_iban: "0",
    shipping_cost: "5",
    shipping_cost_usd: "20.00",
    flag: "🇷🇼",
  },
  {
    id: "187",
    country_code: "WS",
    country_name: "Samoa",
    phonecode: "685",
    iso3: "882",
    status: "0",
    is_iban: "0",
    europe_country: "0",
    solaris_iban: "0",
    shipping_cost: "5",
    shipping_cost_usd: "20.00",
    flag: "🇼🇸",
  },
  {
    id: "188",
    country_code: "SM",
    country_name: "San Marino",
    phonecode: "378",
    iso3: "674",
    status: "0",
    is_iban: "1",
    europe_country: "1",
    solaris_iban: "0",
    shipping_cost: "5",
    shipping_cost_usd: "20.00",
    flag: "🇸🇲",
  },
  {
    id: "190",
    country_code: "SA",
    country_name: "Saudi Arabia",
    phonecode: "966",
    iso3: "682",
    status: "0",
    is_iban: "0",
    europe_country: "0",
    solaris_iban: "0",
    shipping_cost: "5",
    shipping_cost_usd: "20.00",
    flag: "🇸🇦",
  },
  {
    id: "191",
    country_code: "SN",
    country_name: "Senegal",
    phonecode: "221",
    iso3: "686",
    status: "0",
    is_iban: "0",
    europe_country: "0",
    solaris_iban: "0",
    shipping_cost: "5",
    shipping_cost_usd: "20.00",
    flag: "🇸🇳",
  },
  {
    id: "192",
    country_code: "RS",
    country_name: "Serbia",
    phonecode: "381",
    iso3: "688",
    status: "0",
    is_iban: "1",
    europe_country: "0",
    solaris_iban: "0",
    shipping_cost: "5",
    shipping_cost_usd: "20.00",
    flag: "🇷🇸",
  },
  {
    id: "193",
    country_code: "SC",
    country_name: "Seychelles",
    phonecode: "248",
    iso3: "690",
    status: "0",
    is_iban: "0",
    europe_country: "0",
    solaris_iban: "0",
    shipping_cost: "5",
    shipping_cost_usd: "20.00",
    flag: "🇸🇨",
  },
  {
    id: "194",
    country_code: "SL",
    country_name: "Sierra Leone",
    phonecode: "232",
    iso3: "694",
    status: "0",
    is_iban: "0",
    europe_country: "0",
    solaris_iban: "0",
    shipping_cost: "5",
    shipping_cost_usd: "20.00",
    flag: "🇸🇱",
  },
  {
    id: "195",
    country_code: "SG",
    country_name: "Singapore",
    phonecode: "65",
    iso3: "702",
    status: "0",
    is_iban: "0",
    europe_country: "0",
    solaris_iban: "0",
    shipping_cost: "5",
    shipping_cost_usd: "20.00",
    flag: "🇸🇬",
  },
  {
    id: "196",
    country_code: "SK",
    country_name: "Slovakia",
    phonecode: "421",
    iso3: "703",
    status: "0",
    is_iban: "1",
    europe_country: "1",
    solaris_iban: "0",
    shipping_cost: "5",
    shipping_cost_usd: "20.00",
    flag: "🇸🇰",
  },
  {
    id: "197",
    country_code: "SI",
    country_name: "Slovenia",
    phonecode: "386",
    iso3: "705",
    status: "0",
    is_iban: "0",
    europe_country: "0",
    solaris_iban: "0",
    shipping_cost: "5",
    shipping_cost_usd: "20.00",
    flag: "🇸🇮",
  },
  {
    id: "200",
    country_code: "ZA",
    country_name: "South Africa",
    phonecode: "27",
    iso3: "710",
    status: "0",
    is_iban: "0",
    europe_country: "0",
    solaris_iban: "0",
    shipping_cost: "5",
    shipping_cost_usd: "20.00",
    flag: "🇿🇦",
  },
  {
    id: "202",
    country_code: "ES",
    country_name: "Spain",
    phonecode: "34",
    iso3: "724",
    status: "0",
    is_iban: "1",
    europe_country: "1",
    solaris_iban: "1",
    shipping_cost: "5",
    shipping_cost_usd: "20.00",
    flag: "🇪🇸",
  },
  {
    id: "210",
    country_code: "SE",
    country_name: "Sweden",
    phonecode: "46",
    iso3: "752",
    status: "0",
    is_iban: "1",
    europe_country: "1",
    solaris_iban: "0",
    shipping_cost: "5",
    shipping_cost_usd: "20.00",
    flag: "🇸🇪",
  },
  {
    id: "211",
    country_code: "CH",
    country_name: "Switzerland",
    phonecode: "41",
    iso3: "756",
    status: "0",
    is_iban: "1",
    europe_country: "1",
    solaris_iban: "0",
    shipping_cost: "5",
    shipping_cost_usd: "20.00",
    flag: "🇨🇭",
  },
  {
    id: "213",
    country_code: "TW",
    country_name: "Taiwan",
    phonecode: "886",
    iso3: "158",
    status: "0",
    is_iban: "0",
    europe_country: "0",
    solaris_iban: "0",
    shipping_cost: "5",
    shipping_cost_usd: "20.00",
    flag: "🇹🇼",
  },
  {
    id: "214",
    country_code: "TJ",
    country_name: "Tajikistan",
    phonecode: "992",
    iso3: "762",
    status: "0",
    is_iban: "0",
    europe_country: "0",
    solaris_iban: "0",
    shipping_cost: "5",
    shipping_cost_usd: "20.00",
    flag: "🇹🇯",
  },
  {
    id: "215",
    country_code: "TZ",
    country_name: "Tanzania, United Republic of",
    phonecode: "255",
    iso3: "834",
    status: "0",
    is_iban: "0",
    europe_country: "0",
    solaris_iban: "0",
    shipping_cost: "5",
    shipping_cost_usd: "20.00",
    flag: "🇹🇿",
  },
  {
    id: "216",
    country_code: "TH",
    country_name: "Thailand",
    phonecode: "66",
    iso3: "764",
    status: "0",
    is_iban: "0",
    europe_country: "0",
    solaris_iban: "0",
    shipping_cost: "5",
    shipping_cost_usd: "20.00",
    flag: "🇹🇭",
  },
  {
    id: "217",
    country_code: "TG",
    country_name: "Togo",
    phonecode: "228",
    iso3: "768",
    status: "0",
    is_iban: "0",
    europe_country: "0",
    solaris_iban: "0",
    shipping_cost: "5",
    shipping_cost_usd: "20.00",
    flag: "🇹🇬",
  },
  {
    id: "218",
    country_code: "TK",
    country_name: "Tokelau",
    phonecode: "690",
    iso3: "772",
    status: "0",
    is_iban: "0",
    europe_country: "0",
    solaris_iban: "0",
    shipping_cost: "5",
    shipping_cost_usd: "20.00",
    flag: "🇹🇰",
  },
  {
    id: "219",
    country_code: "TO",
    country_name: "Tonga",
    phonecode: "676",
    iso3: "776",
    status: "0",
    is_iban: "0",
    europe_country: "0",
    solaris_iban: "0",
    shipping_cost: "5",
    shipping_cost_usd: "20.00",
    flag: "🇹🇴",
  },
  {
    id: "221",
    country_code: "TN",
    country_name: "Tunisia",
    phonecode: "216",
    iso3: "788",
    status: "0",
    is_iban: "0",
    europe_country: "0",
    solaris_iban: "0",
    shipping_cost: "5",
    shipping_cost_usd: "20.00",
    flag: "🇹🇳",
  },
  {
    id: "222",
    country_code: "TR",
    country_name: "Turkey",
    phonecode: "90",
    iso3: "792",
    status: "0",
    is_iban: "0",
    europe_country: "0",
    solaris_iban: "0",
    shipping_cost: "5",
    shipping_cost_usd: "20.00",
    flag: "🇹🇷",
  },
  {
    id: "223",
    country_code: "TM",
    country_name: "Turkmenistan",
    phonecode: "993",
    iso3: "795",
    status: "0",
    is_iban: "0",
    europe_country: "0",
    solaris_iban: "0",
    shipping_cost: "5",
    shipping_cost_usd: "20.00",
    flag: "🇹🇲",
  },
  {
    id: "225",
    country_code: "TV",
    country_name: "Tuvalu",
    phonecode: "688",
    iso3: "798",
    status: "0",
    is_iban: "0",
    europe_country: "0",
    solaris_iban: "0",
    shipping_cost: "5",
    shipping_cost_usd: "20.00",
    flag: "🇹🇻",
  },
  {
    id: "226",
    country_code: "UG",
    country_name: "Uganda",
    phonecode: "256",
    iso3: "800",
    status: "0",
    is_iban: "0",
    europe_country: "0",
    solaris_iban: "0",
    shipping_cost: "5",
    shipping_cost_usd: "20.00",
    flag: "🇺🇬",
  },
  {
    id: "227",
    country_code: "UA",
    country_name: "Ukraine",
    phonecode: "380",
    iso3: "804",
    status: "0",
    is_iban: "0",
    europe_country: "0",
    solaris_iban: "0",
    shipping_cost: "5",
    shipping_cost_usd: "20.00",
    flag: "🇺🇦",
  },
  {
    id: "228",
    country_code: "AE",
    country_name: "United Arab Emirates",
    phonecode: "971",
    iso3: "784",
    status: "0",
    is_iban: "0",
    europe_country: "0",
    solaris_iban: "0",
    shipping_cost: "5",
    shipping_cost_usd: "20.00",
    flag: "🇦🇪",
  },
  {
    id: "229",
    country_code: "GB",
    country_name: "United Kingdom",
    phonecode: "44",
    iso3: "826",
    status: "0",
    is_iban: "1",
    europe_country: "1",
    solaris_iban: "0",
    shipping_cost: "5",
    shipping_cost_usd: "20.00",
    flag: "🇬🇧",
  },
  {
    id: "230",
    country_code: "US",
    country_name: "United States",
    phonecode: "1",
    iso3: "840",
    status: "0",
    is_iban: "0",
    europe_country: "0",
    solaris_iban: "0",
    shipping_cost: "5",
    shipping_cost_usd: "20.00",
    flag: "🇺🇸",
  },
  {
    id: "232",
    country_code: "UY",
    country_name: "Uruguay",
    phonecode: "598",
    iso3: "858",
    status: "0",
    is_iban: "0",
    europe_country: "0",
    solaris_iban: "0",
    shipping_cost: "5",
    shipping_cost_usd: "20.00",
    flag: "🇺🇾",
  },
  {
    id: "233",
    country_code: "UZ",
    country_name: "Uzbekistan",
    phonecode: "998",
    iso3: "860",
    status: "0",
    is_iban: "0",
    europe_country: "0",
    solaris_iban: "0",
    shipping_cost: "5",
    shipping_cost_usd: "20.00",
    flag: "🇺🇿",
  },
  {
    id: "234",
    country_code: "VU",
    country_name: "Vanuatu",
    phonecode: "678",
    iso3: "548",
    status: "0",
    is_iban: "0",
    europe_country: "0",
    solaris_iban: "0",
    shipping_cost: "5",
    shipping_cost_usd: "20.00",
    flag: "🇻🇺",
  },
  {
    id: "246",
    country_code: "VE",
    country_name: "Venezuela",
    phonecode: "58",
    iso3: "862",
    status: "0",
    is_iban: "0",
    europe_country: "0",
    solaris_iban: "0",
    shipping_cost: "5",
    shipping_cost_usd: "20.00",
    flag: "🇻🇪",
  },
  {
    id: "242",
    country_code: "YE",
    country_name: "Yemen",
    phonecode: "967",
    iso3: "887",
    status: "0",
    is_iban: "0",
    europe_country: "0",
    solaris_iban: "0",
    shipping_cost: "5",
    shipping_cost_usd: "20.00",
    flag: "🇾🇪",
  },
  {
    id: "244",
    country_code: "ZM",
    country_name: "Zambia",
    phonecode: "260",
    iso3: "894",
    status: "0",
    is_iban: "0",
    europe_country: "0",
    solaris_iban: "0",
    shipping_cost: "5",
    shipping_cost_usd: "20.00",
    flag: "🇿🇲",
  },
];
export const CodegoIncomeSources = [
  "Salary",
  "Investment",
  "Real Estate",
  "Agriculture",
];
